### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by asmagen** [jlevy44/PathFlowAI#14]
Hello @jlevy44 

Is this pipeline working with registration of different marker stains of the same tissue?
I noticed you encountered a similar problem to what I am experiencing with drop2 where the registered image output is in gray scale and in order to get the original RGB image warped I need to apply the deformation fields using griddata function which doesn't scale to anything close to the size of pathology images. One solution is of course tiling but the process of combining their overlap will be very tedious. I hope you have an insight into this problem.

Thanks

**Comment by jlevy44** [comment]
Hi @asmagen ! Very nice of you to mention this critical issue. Recently, we have a work under review which focuses on scaling registration approaches to giga-pixel whole slide images: https://github.com/jlevy44/PathFlow-MixMatch and we do compare results to drop2 (as you had mentioned, we had to subsample the WSI when using drop2, which is less than ideal). We do note that this approach right now is proof of concept, is undergoing additional validation, adding help docs, and modification to hopefully scale up these analyses and very much welcomes community contributions. After additional development, MixMatch will be integrated as a PathFlowAI "module" so-to-speak. I would recommend in addition to the MixMatch trying to tile the resulting registered tissue segments and trying additional alignment; you should still be able to preserve the quality of the original slide if done right.

You can find the preliminary work here: https://www.biorxiv.org/content/10.1101/2020.03.22.002402v1

We do note that if you are registering different marker stains of the same tissue, registration of different tissue sections will not perfectly align the micro architecture (eg. nuclei) of the tissue sections because the collection of these features are different across different layers of the tissue. If possible, destaining  and restaining is  a way to get a more perfect alignment if you are not already doing so.   

There's more I can comment here, but these are my initial thoughts. I am more than happy to have an additional discussion here.

**Comment by jlevy44** [comment]
Discussion has been moved to: https://github.com/jlevy44/PathFlow-MixMatch/issues/1
